const express = require('express');
const router = require('./router');
const {validaSenha, validaDados} = require('./middleware');
const app = express();
const port = 8000;
app.use(express.json());
app.use(validaSenha);
app.use(validaDados);
app.use(router);
app.listen(port);